spring:
  config:
    import: application-common-local.yml

#kafka:
#  bootstrapServer: localhost:9092
#  producer:
#    ack: all
#  topic:
#    api: temp-api-topic1
#    db2db: temp-api-topic1
#    log: temp-api-log1

encrypt:
  key-store:
    location: classpath:skeleton.pkcs12
    password: Qordpsem23129!
    alias: private
    secret: Qordpsem23129!
    type: pkcs12

logging:
  file:
    path: ./logs