server:
  port: 8081
  shutdown: graceful

spring:
  config:
    import: application-common.yml
  application:
    name: <%=project.parent.name%>-<%=project.name%><%=project.qualifier?'@'+qualifier:''%>
    version: <%=project.version%>
  profiles:
    active: <%=profile%>
  main:
    banner-mode: off

#springdoc
springdoc:
  info:
    title: <%=project.parent.name%>-<%=project.name%>
    description: <%=project.parent.name%>-<%=project.name%> docs for \${spring.profiles.active}
    contact:
      name: STDev Team
      email: STDev.team@qoo10.com
      url: https://jira.qoo10.it/browse/TM-801


